Hydrocraft = Hydrocraft or {}
Hydrocraft.OnCreate = Hydrocraft.OnCreate or {}

--all possible seed packets, both vanilla and Hydrocraft
local allSeedPackets = {
  "Hydrocraft.HCBeetsugarseedpacket",
  "Hydrocraft.HCOreganoseedspacket",
  "Hydrocraft.HCWheatseedpacket",
  "Hydrocraft.HCLimeseedspacket",
  "Hydrocraft.HCGrapesgreenseedspacket",
  "Hydrocraft.HCDateseedspacket",
  "Hydrocraft.HCFigseedspacket",
  "Hydrocraft.HCKiwiseedspacket",
  "Hydrocraft.HCPlumseedspacket",
  "Hydrocraft.HCPersimmonseedspacket",
  "Hydrocraft.HCCauliflowerseedspacket",
	--"Hydrocraft.HCJalapenoseedspacket", --this was already commented out
  "Hydrocraft.HCSquashsummerseedspacket",
  "Hydrocraft.HCTomatocherryseedspacket",
  "Hydrocraft.HCMulberryseedspacket",
	"Hydrocraft.HCSpinachseedspacket",
  "Hydrocraft.HCCeleryseedspacket,
  "Hydrocraft.HCBasilseedspacket",
  "Hydrocraft.HCAsparagusseedspacket",
  "Hydrocraft.HCArtichokesseedspacket",
  "Hydrocraft.HCAlfalfaseedspacket",
  "Hydrocraft.HCBambooseedspacket",
  "Hydrocraft.HCJuteseedspacket",
  "Hydrocraft.HCSpirulinaseedspacket",
  "Hydrocraft.HCRubbertreeseedspacket",
  "Hydrocraft.HCRiceseedspacket",
  "Hydrocraft.HCGingerseedspacket",
  "Hydrocraft.HCTomatilloseedspacket",
  "Hydrocraft.HCChiligreenseedspacket",
  "Hydrocraft.HCPricklypearseedspacket",
  "Hydrocraft.HCAgaveblueseedspacket",
  "Hydrocraft.HCCactusseedspacket",
  "Hydrocraft.HCHempseedspacket",
  "Hydrocraft.HCPoppyseedspack",
  "Hydrocraft.HCChilipepperseedspacket",
  "Hydrocraft.HCTobaccoseedspacket",
  "farming.CabbageBagSeed",
  "farming.PotatoBagSeed",
  "farming.TomatoBagSeed",
  "farming.StrewberrieBagSeed",
  "farming.RedRadishBagSeed",
  "farming.BroccoliBagSeed",
  "farming.CarrotBagSeed",
  "Hydrocraft.HCPotatogoldenseedspacket",
  "Hydrocraft.HCPotatoredseedspacket",
  "Hydrocraft.HCCabbagewhiteseedspacket",
  "Hydrocraft.HCCabbageredseedspacket",
  "Hydrocraft.HCCottonseedspacket",
  "Hydrocraft.HCColewortseedspacket",
  "Hydrocraft.HCApricotseedspacket",
  "Hydrocraft.HCCornblueseedspacket",
  "Hydrocraft.HCCornredseedspacket",
  "Hydrocraft.HCCornwhiteseedspacket",
  "Hydrocraft.HCPumpkinbuskinseedspacket",
  "Hydrocraft.HCPumpkingreenseedspacket",
  "Hydrocraft.HCPumpkinwhiteseedspacket",
  "Hydrocraft.HCPumpkinlargeseedspacket",
  "Hydrocraft.HCPotatosweetseedspacket",
  "Hydrocraft.HCOniongreenseedspacket",
  "Hydrocraft.HCGarlicseedspacket",
  "Hydrocraft.HCCucumberseedspacket",
  "Hydrocraft.HCChinesecabbageseedspacket",
  "Hydrocraft.HCZucchiniseedspacket",
  "Hydrocraft.HCPineappleseedspacket",
  "Hydrocraft.HCCherryseedspacket",
  "Hydrocraft.HCPearseedspacket",
  "Hydrocraft.HCAvacadoseedspacket",
  "Hydrocraft.HCPeanutseedspacket",
  "Hydrocraft.HCPeaseedspacket",
  "Hydrocraft.HCOnionseedspacket",
  "Hydrocraft.HCLettuceseedspacket",
  "Hydrocraft.HCLeekseedspacket",
  "Hydrocraft.HCEggplantseedspacket",
  "Hydrocraft.HCCornseedspacket",
  "Hydrocraft.HCBellpepperyellowseedspacket",
  "Hydrocraft.HCBellpepperredseedspacket",
  "Hydrocraft.HCBellpeppergreenseedspacket",
  "Hydrocraft.HCWatermelonseedspacket",
  "Hydrocraft.HCPeachseedspacket",
  "Hydrocraft.HCOrangeseedspacket",
  "Hydrocraft.HCLemonseedspacket",
  "Hydrocraft.HCGrapeseedspacket",
  "Hydrocraft.HCBlueberryseedspacket",
  "Hydrocraft.HCBlackberryseedspacket",
  "Hydrocraft.HCBananaseedspacket",
  "Hydrocraft.HCAppleseedspacket",
  "Hydrocraft.HCTeaseedspacket",
  "Hydrocraft.HCPumpkinseedspacket",
  "Hydrocraft.HCBeanseedspacket"		
}

--Untested, & not used anywhere
--Intended for use in recipe 'Identify Unknown Seeds' (HC_Seeds.txt)
--designed to replace the awful HCRandomseeds function in /server/SeedsHCExtra.lua
function Hydrocraft.OnCreate.RandomSeedPacket(items, result, player)
  local r = ZombRand(#allSeedPackets)
  local packet = allSeedPackets[r + 1]
  player:getInventory():AddItem(packet)
end
